// controllers/billingController.js
const db = require('../config/database');

const processCheckout = async (req, res) => {
    const { transaction, items } = req.body;
    
    // Grab the ID of the owner/employee who is currently logged in
    const userId = req.user.id; 

    const connection = await db.getConnection();

    try {
        // Start the All-or-Nothing Transaction
        await connection.beginTransaction();

        // ==========================================
        // STEP 1 & 4: Validate Stock BEFORE doing anything
        // ==========================================
        // Step 1: Aggregate quantities by product_id
        const productTotals = {};
        for (let item of items) {
            if (!productTotals[item.product_id]) {
                productTotals[item.product_id] = 0;
            }
            productTotals[item.product_id] += item.quantity;
        }

        // Step 2: Validate aggregated quantities
        for (let productId in productTotals) {
            const [productRows] = await connection.query(
                'SELECT name, stock_qty FROM Products WHERE id = ? FOR UPDATE',
                [productId]
            );

            if (productRows.length === 0) {
                throw new Error(`Product is no longer in the database.`);
            }

            const currentStock = productRows[0].stock_qty;
            const productName = productRows[0].name;
            const totalRequested = productTotals[productId];

            if (currentStock < totalRequested) {
                throw new Error(`Cannot complete sale! You only have ${currentStock} units of "${productName}" but tried to sell ${totalRequested}.`);
            }
        }

        // ==========================================
        // STEP 2: Create the Master Transaction Record
        // ==========================================
        // (sale_date is automatically generated by MySQL if your schema is set up correctly)
        const [transactionResult] = await connection.query(
            'INSERT INTO Transactions (sub_total, discount_amount, final_amount, user_id) VALUES (?, ?, ?, ?)',
            [transaction.sub_total, transaction.discount_amount, transaction.final_amount, userId]
        );
        const transactionId = transactionResult.insertId;

        // ==========================================
        // STEP 3: Insert Items and Deduct Inventory
        // ==========================================
        for (let item of items) {
            // A. Log the individual item sold
            await connection.query(
                'INSERT INTO Transaction_Items (transaction_id, product_id, quantity, price_at_sale) VALUES (?, ?, ?, ?)',
                [transactionId, item.product_id, item.quantity, item.price_at_sale]
            );
        }

        // Deduct inventory using aggregated quantities
        for (let productId in productTotals) {
            await connection.query(
                'UPDATE Products SET stock_qty = stock_qty - ? WHERE id = ?',
                [productTotals[productId], productId]
            );
        }

        // 🔓 If we made it here, everything is mathematically sound. SAVE IT!
        await connection.commit();
        res.status(201).json({ message: "Sale completed successfully!", transactionId });

    } catch (error) {
        // ❌ Undo EVERYTHING if the stock check failed or a database error occurred
        await connection.rollback();
        console.error("Checkout Error:", error);
        
        // Send the specific error message back to the React frontend
        res.status(400).json({ error: error.message || "Checkout failed due to a server error." });
    } finally {
        connection.release();
    }
};

// 1. Get the list of all sales (Master Record)
const getSalesHistory = async (req, res) => {
    try {
        // Fetch ordered by newest first
        const [rows] = await db.query('SELECT * FROM Transactions ORDER BY id DESC');
        res.status(200).json(rows);
    } catch (error) {
        console.error(error);
        res.status(500).json({ error: "Failed to fetch sales history" });
    }
};

// 2. Get the specific items for ONE sale (Detail Record)
const getTransactionItems = async (req, res) => {
    try {
        const transactionId = req.params.id;
        
        // JOIN transaction_items with Products to get the real name
        const sql = `
            SELECT 
                p.name AS product_name,
                ti.quantity,
                ti.price_at_sale,
                (ti.quantity * ti.price_at_sale) AS total_price
            FROM Transaction_Items ti
            JOIN Products p ON ti.product_id = p.id
            WHERE ti.transaction_id = ?
        `;
        
        const [rows] = await db.query(sql, [transactionId]);
        res.status(200).json(rows);
    } catch (error) {
        console.error(error);
        res.status(500).json({ error: "Failed to fetch transaction items" });
    }
};

module.exports = { processCheckout, getSalesHistory, getTransactionItems };