// controllers/billingController.js
const db = require('../config/database');

const processCheckout = async (req, res) => {
    const { transaction, items } = req.body;
    
    // Grab the ID of the owner/employee who is currently logged in
    const userId = req.user.id; 

    const connection = await db.getConnection();

    try {
        // Start the All-or-Nothing Transaction
        await connection.beginTransaction();

        // ==========================================
        // STEP 1 & 4: Validate Stock BEFORE doing anything
        // ==========================================
        for (let item of items) {
            // 'FOR UPDATE' temporarily locks this row. It prevents race conditions
            // if two cashiers try to sell the last bottle at the exact same time!
            const [productRows] = await connection.query(
                'SELECT name, stock_qty FROM Products WHERE id = ? FOR UPDATE',
                [item.product_id]
            );

            if (productRows.length === 0) {
                throw new Error(`Product is no longer in the database.`);
            }

            const currentStock = productRows[0].stock_qty;
            const productName = productRows[0].name;

            // THE GUARDRAIL: If they try to sell more than they have, trigger the rollback!
            if (currentStock < item.quantity) {
                throw new Error(`Cannot complete sale! You only have ${currentStock} units of "${productName}" left in stock.`);
            }
        }

        // ==========================================
        // STEP 2: Create the Master Transaction Record
        // ==========================================
        // (sale_date is automatically generated by MySQL if your schema is set up correctly)
        const [transactionResult] = await connection.query(
            'INSERT INTO transactions (sub_total, discount_amount, final_amount, user_id) VALUES (?, ?, ?, ?)',
            [transaction.sub_total, transaction.discount_amount, transaction.final_amount, userId]
        );
        const transactionId = transactionResult.insertId;

        // ==========================================
        // STEP 3: Insert Items and Deduct Inventory
        // ==========================================
        for (let item of items) {
            // A. Log the individual item sold
            await connection.query(
                'INSERT INTO transaction_items (transaction_id, product_id, quantity, price_at_sale) VALUES (?, ?, ?, ?)',
                [transactionId, item.product_id, item.quantity, item.price_at_sale]
            );

            // B. Subtract the sold quantity from the main inventory
            await connection.query(
                'UPDATE Products SET stock_qty = stock_qty - ? WHERE id = ?',
                [item.quantity, item.product_id]
            );
        }

        // 🔓 If we made it here, everything is mathematically sound. SAVE IT!
        await connection.commit();
        res.status(201).json({ message: "Sale completed successfully!", transactionId });

    } catch (error) {
        // ❌ Undo EVERYTHING if the stock check failed or a database error occurred
        await connection.rollback();
        console.error("Checkout Error:", error);
        
        // Send the specific error message back to the React frontend
        res.status(400).json({ error: error.message || "Checkout failed due to a server error." });
    } finally {
        connection.release();
    }
};

module.exports = { processCheckout };